services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dokkan-app
    container_name: dokkan-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - dokkan-network

  web:
    image: nginx:alpine
    container_name: dokkan-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - dokkan-network

  db:
    image: mysql:8.0
    container_name: dokkan-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    networks:
      - dokkan-network

networks:
  dokkan-network:
    driver: bridge
